name: Test

env:
  PROJECT_NAME: swiss-qr-bill-decoder
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: aarch64-apple-darwin
            runner: macos-latest
            cross: false
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
            cross: true
          - target: aarch64-unknown-linux-musl
            runner: ubuntu-latest
            cross: true
          - target: i686-unknown-linux-gnu
            runner: ubuntu-latest
            cross: true
          - target: i686-unknown-linux-musl
            runner: ubuntu-latest
            cross: true
          - target: x86_64-apple-darwin
            runner: macos-latest
            cross: false
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            cross: false
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
            cross: false

    steps:
    - name: Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Install Rust
      uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      with:
        targets: "${{ matrix.platform.target }}"

    - name: Install cross
      uses: taiki-e/install-action@cf39a74df4a72510be4e5b63348d61067f11e64a # v2
      if: matrix.platform.cross
      with:
        tool: cross

    - name: Rust (Cargo) Caching
      uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

    - name: Build
      env:
        CARGO: ${{ matrix.platform.cross && 'cross' || 'cargo' }}
      run: |
        $CARGO test \
          --target ${{ matrix.platform.target }} \
          --no-run \
          --locked

    - name: Run tests
      env:
        CARGO: ${{ matrix.platform.cross && 'cross' || 'cargo' }}
      run: |
        $CARGO test \
          --target ${{ matrix.platform.target }} \
          --locked
